services:
  api-fornecedor:
    build: .
    image: ms-api-fornecedor:v1
    container_name: ms-api-fornecedor
    ports:
      - "3000:3000"
    env_file:
      - .env
    command: npm run start
    environment:
      - TZ=${TZ}